version: '2'
services:
  web:
    image: 'olsynt/angular-fullstack:$CF_BRANCH'
    environment:
      - MONGODB_DOCKER_SERVICE=mongo
      - PORT=8080
    ports:
      - 3000
  mongo:
    image: 'mongo:latest'
    ports:
      - 27017
